
all:
	(cd system/source;$(MAKE))
	(cd pokerlib/source;$(MAKE))
	(cd server/source;$(MAKE))
clean:
	(cd system/source;$(MAKE) clean)
	(cd pokerlib/source;$(MAKE) clean)
	(cd server/source;$(MAKE) clean)
